export const projects = [
  {
    id: 1,
    title: "murk",
    tech: ["C#", "Unity", "Procreate"],
    desc: "It is a single-player endless game, where you must dodge obstacles, collect stars and complete tasks.",
    projectLink: "https://shrutz.com/",
    githubLink: "https://github.com/shrutishri2208/murk",
  },
  {
    id: 2,
    title: "netflix-clone",
    tech: [
      "react.js",
      "react-router",
      "redux",
      "redux-persist",
      "tailwindcss",
      "material UI",
      "Rapid API",
    ],
    desc: "Build with react.js an integrates Netflix API from Rapid API. Uses redux for state management, react-router for configuring states and redux-persist to store state in local storage.",
    projectLink: "",
    githubLink: "https://github.com/shrutishri2208/netflix-clone",
  },
  {
    id: 3,
    title: "UI components",
    tech: ["react.js", "CSS"],
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
    projectLink: "",
    githubLink: "https://github.com/shrutishri2208/UI-components",
  },
  {
    id: 4,
    title: "voting application",
    tech: ["hardhat", "ether.js", "react.js"],
    desc: "It is a decentralized application that can be used for casting and recording votes. The user can connect his wallet and vote for his preferred candidate once.",
    projectLink: "",
    githubLink: "https://github.com/shrutishri2208/election-portal",
  },
  {
    id: 5,
    title: "wave portal",
    tech: ["hardhat", "ether.js", "HTML", "CSS"],
    desc: "It is a simple profile site where you can request test ethers after every 10 minutes, by connecting your Ethereum wallet.",
    projectLink: "",
    githubLink: "https://github.com/shrutishri2208/wave-portal",
  },
  {
    id: 6,
    title: "portfolio site",
    tech: ["react.js", "tailwindcss", "material UI"],
    desc: "A clean looking profile site built with react.js showcasing projects and resume.",
    projectLink: "",
    githubLink: "https://github.com/shrutishri2208/portfolio",
  },
  {
    id: 7,
    title: "website for murk",
    tech: ["HTML", "CSS", "javascript"],
    desc: "Website made with pure HTML, CSS and Javascript to promote the game MURK.",
    projectLink: "",
    githubLink: "https://github.com/shrutishri2208/murksite",
  },
];

//WAVE PORTAL
